# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lhoodcpp <- function(eta, beta, doc_ct, mu, siginv) {
    .Call(`_stm_lhoodcpp`, eta, beta, doc_ct, mu, siginv)
}

gradcpp <- function(eta, beta, doc_ct, mu, siginv) {
    .Call(`_stm_gradcpp`, eta, beta, doc_ct, mu, siginv)
}

multilhoodcpp <- function(eta, beta, doc_ct, mu, pi, siginv) {
    .Call(`_stm_multilhoodcpp`, eta, beta, doc_ct, mu, pi, siginv)
}

multigradcpp <- function(eta, beta, doc_ct, mu, pi, siginv) {
    .Call(`_stm_multigradcpp`, eta, beta, doc_ct, mu, pi, siginv)
}

multihpbcpp <- function(eta, beta, doc_ct, mu, siginv, sigmaentropy, sigs, 
                        sigsentropy, omegaentropy, sigs_inv, omega) {
    .Call(`_stm_multihpbcpp`, eta, beta, doc_ct, mu, siginv, sigmaentropy, sigs,
          sigsentropy, omegaentropy, sigs_inv, omega)
}

singlehpbcpp <- function(eta, beta, doc_ct, mu, siginv, sigmaentropy) {
    .Call(`_stm_singlehpbcpp`, eta, beta, doc_ct, mu, siginv, sigmaentropy)
}


